---
name: Class-Attribute
version: 0.024
author:
  - 'Bharanee Rathna <deepfryed à gmail>'
abstract: A fast and light weight alternative for defining class attributes.
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Class::Accessor: 0
  Test::Exception: 0
  Test::More: 0
  Test::NoWarnings: 0
provides:
  Class::Attribute:
    file: lib/Class/Attribute.pm
    version: 0.024
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
